### ISSUE TITLE
Allow explicit reloading of mappings

### ISSUE THREAD

**Issue by nullpainter** [dadoonet/spring-elasticsearch#24]
I have mappings defined in `src/main/resources/es/...` and wish to bulk delete records from elasticsearch (in the context of integration tests, as cleanup of data after each test is run). 

The methods I've seen thus far in elasticsearch's Java API all delete the mappings themselves - rather than provide the ability to delete individual records - which is problematic as I can't see a way to reload these via Spring elasticsearch.

I've used the `forceMapping` property on the client bean, however this is only picked up when the bean is initialised rather than between tests.

I imagine I could just search for all records then delete them one-by-one, but a mechanism to recreate mappings would be handy.

**Comment by dadoonet** [comment]
Note: since elasticsearch 2.0, delete by query only exists as a plugin.
I don't think we can really support reloading "mappings" without actually reloading indices, which means removing all indices for a given index while starting.

About auto reloading settings/mappings in tests, I see two options:

* close the previous client and build a new one. This should pickup again settings and mappings
* explicitly call `ElasticsearchAbstractClientFactoryBean#afterPropertiesSet()` like here https://github.com/dadoonet/spring-elasticsearch/blob/master/src/test/java/fr/pilato/spring/elasticsearch/annotation/AppConfig.java#L49-49

I'm closing this but feel free to reopen if you think it does not solve what you were after...
